spring: 
  zipkin:
    base-url: http://localhost:9411
  application: 
    name: olx-api-gateway
  cloud:
    gateway:
      routes:
      - id: masterdata-service
        uri: lb://masterdata-service
        predicates:
        - Path=/olx/masterdata/**
      - id: advertise-service
        uri: lb://advertise-service
        predicates:
        - Path=/olx/advertiseservice/**
      - id: auth-service
        uri: lb://auth-service
        predicates: 
        - Path=/olx/authentication/**
server:
  port: 9191
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true